name: Playwright C# CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build project
        run: dotnet build --no-restore

      #  Install system dependencies for Playwright
      - name: Install Playwright dependencies
        run: npx playwright install-deps  

      # Step 5: Install Playwright browsers
      - name: Install Playwright browsers
        run: pwsh bin/Debug/net6.0/playwright.ps1 install --with-deps

      # Step 6: Run Playwright tests
      - name: Run Playwright Tests
        run: dotnet test --no-build --logger "trx;LogFileName=TestResults.trx"

      # Step 7: Upload Playwright test report (TRX)
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: "**/TestResults/*.trx"
