name: Playwright C# CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Install Playwright browsers
        run: pwsh bin/Debug/net6.0/playwright.ps1 install --with-deps

      - name: Run Playwright Tests
        run: dotnet test --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: "**/TestResults/*.trx"
