name: Playwright CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Show directory structure (for debugging)
      - name: Show directory structure
        run: |
          pwd
          ls -R

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Install Playwright Browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Step 6: Run Playwright tests
      - name: Run Playwright Tests
        run: npx playwright test --reporter=line

      # Step 7: Upload Playwright test report (HTML)
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
